name: Laravel

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  laravel-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Deploy to Hostinger
        env:
          SSH_USER: ${{ secrets.REMOTE_USERNAME }}
          SSH_PASSWORD: ${{ secrets.REMOTE_PASSWORD }}
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -p 65002 $SSH_USER@62.72.37.27 'cd public_html && rm -r ./*'
          sshpass -p "$SSH_PASSWORD" ssh -p 65002 $SSH_USER@62.72.37.27 'cd public_html && git clone git@github.com:benoit-pliss/geez-production.git .'
          sshpass -p "$SSH_PASSWORD" ssh -p 65002 $SSH_USER@62.72.37.27 'cd public_html && composer update --ignore-platform-reqs'
          sshpass -p "$SSH_PASSWORD" ssh -p 65002 $SSH_USER@62.72.37.27 'cd public_html && cp ../.env .env'
          sshpass -p "$SSH_PASSWORD" ssh -p 65002 $SSH_USER@62.72.37.27 'cd public_html && php artisan key:generate'
          sshpass -p "$SSH_PASSWORD" ssh -p 65002 $SSH_USER@62.72.37.27 'cd public_html && php artisan migrate --force'
          sshpass -p "$SSH_PASSWORD" ssh -p 65002 $SSH_USER@62.72.37.27 'cd public_html && php artisan db:seed --force'
