name: Laravel

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Build and Deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Setup SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USERNAME }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.TARGET }}
          script: |
            cd public_html
            git clone git@github.com:benoit-pliss/geez-production.git .
            composer update --ignore-platform-reqs
            cp ../.env .env
            php artisan generate:key
            php artisan migrate
            php artisan DB:seed


