name: Laravel

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
    laravel-tests:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Install dependencies
          run: npm install

        - name: Build
          run: npm run build

        - name: Setup SSH
          run:
            ssh -p {{secret.TARGET}} {{secret.REMOTE_USERNAME}}@{{secret.REMOTE_HOST}} "cd {{secret.REMOTE_PATH}}
               && cd public_html
                && rm -r ./*
                && git clone git@github.com:benoit-pliss/geez-production.git .
                && composer update --ignore-platform-reqs
                && cp ../.env .env
                && php artisan key:generate
                && php artisan migrate --force
                && php artisan DB:seed --force


